openapi: 3.0.0
servers: []
info:
  description: >
    ## Introducción

    En este repositorio, se presenta la solución propuesta para el proyecto integrador de la materia "Tópicos de Ingeniería de Software II". La propuesta implica el desarrollo de un servicio web (API) que ofrece acceso a un modelo de red neuronal.

    
    El objetivo principal de este modelo es diagnosticar el riesgo cardíaco de un paciente a partir de datos clínicos proporcionados, tales como el nivel de colesterol, la presión arterial, el nivel de azúcar en sangre, la edad, el sobrepeso y el hábito de fumar.
    
    ## Integrantes del grupo
    
    - Screpnik, Julieta
    
    - Sánchez, Raúl
    
    ## Repositorio Github
    
    Nuestro código fuente se encuentra en un [repositorio privado en GitHub](https://github.com/fueguino84/tp_final_topicos2).
    
    
    Para obtener acceso al repositorio y colaborar con nosotros, por favor, solicita acceso enviando una solicitud a [julietascrepnik@gmail.com](mailto:julietascrepnik@gmail.com) o a [fueguino84@gmail.com](mailto:fueguino84@gmail.com).


    ¡Gracias por tu interés y apoyo!
  version: 1.0.0
  title: Predictor de Riesgo Cardíaco
  termsOfService: ''
tags:
  - name: API Gateway
  - name: Authenticator
  - name: Predictor
  - name: Logger
paths:
  /predict:
    get:
      summary: 'PredictCardiacRisk'
      description: 'Acceso principal para la predicción de riesgo cardíaco.'
      parameters:
        - name: colesterol
          in: query
          required: false
          schema:
            type: string
            default: '0'
        - name: presion
          in: query
          required: false
          schema:
            type: string
            default: '0'
        - name: glucosa
          in: query
          required: false
          schema:
            type: string
            default: '0'
        - name: edad
          in: query
          required: false
          schema:
            type: string
            default: '0'
        - name: sobrepeso
          in: query
          required: false
          schema:
            type: string
            default: '0'
        - name: tabaquismo
          in: query
          required: false
          schema:
            type: string
            default: '0'
      operationId: ''
      responses:
        '200':
          description: Respuesta correcta
        '400':
          description: Error por valores incorrectos
        '500':
          description: Error al predecir
      tags:
        - API Gateway
      security:
        - api_key: []

    post:
      tags:
        - Predictor
      summary: 'PredictCardiacRisk'
      description: ''
      operationId: ''
      responses:
        '200':
          description: Respuesta correcta
        '500':
          description: Error al realizar la predicción
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                colesterol:
                  type: number
                presion:
                  type: number
                glucosa:
                  type: number
                edad:
                  type: number
                sobrepeso:
                  type: number
                tabaquismo:
                  type: number
  /train_model:
    get:
      tags:
        - API Gateway
      summary: ModelTrain
      description: 'Acceso para el entrenamiento del modelo de la red neuronal.
      
      General el modelo keras (model.keras) y el scaler para los datos de entrada (scaler.joblib).
      
      
      **Nota**: No es necesario ejecutarlo. La aplicación ya cuenta con estos archivos previamente generados.'
      operationId: ''
      responses:
        '200':
          description: Respuesta correcta
        '500':
          description: Error durante el entrenamiento
  /authenticate:
    post:
      tags:
        - Authenticator
      summary: 'AuthenticateUser'
      description: ''
      operationId: ''
      responses:
        '200':
          description: Respuesta correcta
        '401':
          description: Error de autenticación
        '403':
          description: Cuota de usuario excedida
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                start_time:
                  type: number
      security:
        - api_key: []
  /log:
    post:
      summary: 'LogRequest'
      description: ''
      operationId: ''
      responses:
        '200':
          description: Default response
      tags:
        - Logger
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                start_time:
                  type: number
                params:
                  type: string
                response:
                  type: object
                  properties:
                    respuesta:
                      type: string
                    valor:
                      type: string
                elapsed_time:
                  type: number
                end_time:
                  type: number
                user_info:
                  type: object
                  properties:
                    _id:
                      type: object
                      properties:
                        $oid:
                          type: string
                    name:
                      type: string
                    email:
                      type: string
                    apikey:
                      type: string
                    group:
                      type: string
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
security: []
